"""
system/report_writer.py — Daily session report generator.

Compiles today's session log into a human-readable markdown report using
the LLM. Saves to reports/YYYY-MM-DD.md and returns the file path.

Usage:
    from system.report_writer import write_daily_report
    from system.session_logger import session_logger
    path = write_daily_report(session_logger.get_today_log())
"""
from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path

_REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


def write_daily_report(log: list[dict]) -> str:
    """Generate a markdown daily report from the session log.

    Args:
        log: List of session log entries from session_logger.get_today_log().

    Returns:
        Absolute path string to the saved report file.
    """
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    today = datetime.now().strftime("%Y-%m-%d")
    report_path = _REPORTS_DIR / f"{today}.md"

    if not log:
        report = f"# Sam Daily Report — {today}\n\nNo actions logged today.\n"
        _save(report_path, report)
        return str(report_path)

    # Build a condensed log for the LLM
    log_text = "\n".join(
        f"{e['timestamp']} [{e['outcome'].upper()}] {e['intent']}: {e['summary']}"
        for e in log
    )

    try:
        from agent.llm_bridge import agent_llm_call

        system_prompt = (
            "You are Sam, a personal AI assistant. Write a concise daily report "
            "based on the action log provided. Format as markdown with these sections:\n"
            "## Summary (2-3 sentences overview)\n"
            "## Tasks Completed (bullet list)\n"
            "## Pending / Incomplete (bullet list, if any)\n"
            "## Observations (what patterns you noticed, anything worth noting)\n"
            "## Tomorrow (1-2 suggestions based on today's work)\n\n"
            "Be conversational and specific — mention actual file names, app names, "
            "and intents where relevant. Keep total length under 400 words."
        )

        report_body = agent_llm_call(
            system_prompt=system_prompt,
            user_prompt=f"Date: {today}\n\nAction Log:\n{log_text}",
            require_json=False,
        )

        if not report_body:
            report_body = _fallback_report(log)

        report = f"# Sam Daily Report — {today}\n\n{report_body}\n\n---\n*Generated by Sam at {datetime.now().strftime('%H:%M')}*\n"

    except Exception as e:
        report = f"# Sam Daily Report — {today}\n\n{_fallback_report(log)}\n\n*(LLM generation failed: {e})*\n"

    _save(report_path, report)
    return str(report_path)


def _fallback_report(log: list[dict]) -> str:
    """Simple text report when LLM is unavailable."""
    lines = ["## Actions Today\n"]
    completed = [e for e in log if e["outcome"] == "done"]
    errors    = [e for e in log if e["outcome"] == "error"]

    for e in completed:
        lines.append(f"- [{e['timestamp']}] {e['summary']}")
    if errors:
        lines.append("\n## Errors\n")
        for e in errors:
            lines.append(f"- [{e['timestamp']}] {e['summary']}")
    return "\n".join(lines)


def _save(path: Path, content: str):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
