@echo off
echo Starting Chrome with remote debugging...
"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --remote-allow-origins=* --user-data-dir="C:\chrome-debug-profile"
